CREATE TABLE TBL_DEVELOPER(				
	ID VARCHAR2(15),
	PASSWORD VARCHAR2(15),
	DUID VARCHAR2(20),
	DNAME VARCHAR2(5),			
	DLANGUAGE VARCHAR2(10),			
	NOWSTATUS CHAR(1),			
	GROUPUID VARCHAR2(20),			
	REGISTDAY DATE,			
	ENDPROCNT VARCHAR2(3),			
	DSTATUS CHAR(1),			
	DPHONE CHAR(11),			
	DUTY VARCHAR2(5),
	PRIMARY KEY(DUID, GROUPUID)
);	
SELECT * FROM TBL_DEVELOPER
CREATE TABLE TBL_GROUP (				
	GUID VARCHAR2(20),			
	GNAME VARCHAR2(10),			
	GCONTENTS VARCHAR2(10),			
	REGISTERDAY DATE,			
	GSTATUS CHAR(1),			
	GROUPLEADER VARCHAR2(20),
	PRIMARY KEY(GUID),
	CONSTRAINT TBL_GROUP_PK PRIMARY KEY (GUID, GROUPLEADER),
	CONSTRAINT TBL_GROUP_FK FOREIGN KEY (GUID, GROUPLEADER) REFERENCES TBL_DELVEROPER(GROUPUID, DUID)
);				
DROP TABLE TBL_DEVELOPER

DROP TABLE TBL_GROUP
SELECT * FROM TBL_AUTH
--SELECT DBMS_RANDOM.STRING('A', 15) STR FROM DUAL; UID »ý¼º
INSERT INTO TBL_AUTH VALUES('admin','1234', DBMS_RANDOM.STRING('A', 15));